# Generated by Django 5.1.6 on 2025-12-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QadaaSalat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='تاريخ بداية ترك الصلاة')),
                ('repentance_date', models.DateField(help_text='تاريخ التوبة')),
                ('daily_qadaa', models.PositiveIntegerField(help_text='عدد الصلوات المقضية يوميًا')),
                ('completed_prayers', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
