# Generated by Django 5.1.6 on 2025-12-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_date', models.DateField()),
                ('prayer_name', models.CharField(choices=[('Fajr', 'الفجر'), ('Dhuhr', 'الظهر'), ('Asr', 'العصر'), ('Maghrib', 'المغرب'), ('Isha', 'العشاء')], max_length=10)),
                ('done', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QadaaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='تاريخ بداية ترك الصلاة')),
                ('repentance_date', models.DateField(help_text='تاريخ التوبة')),
            ],
        ),
    ]
